url: "https://alterego.clothing"
highlighter: pygments

# Permalinks
permalink: pretty

# Server
baseurl: /
encoding: UTF-8

languages: ['en', 'zh', 'id']
languages_text: ['English', '中文', 'Bahasa Indonesia']
language_default: 'en'
exclude_from_localizations: ['Gemfile', 'Gemfile.lock', 'CNAME', 'robots.txt', 'js', 'images', 'css', 'assets']

lang:
  en: "English"
  id: "Indonesia"
  zh: "Chinese"

analytics:
  google:
    account: UA-43024238-2
    domain: "alterego.clothing"

gems:
  - jekyll-sitemap